name: Test

on:
  pull_request:
  push:
    paths-ignore:
      - '*.md'

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      #----------------------------------------------
      #       setup Poetry & install dependencies
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install --no-interaction
      #----------------------------------------------
      #       run pytest
      #----------------------------------------------
      - name: Run pytest
        run: poetry run pytest

  # Build & install: run az-switch help command
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Build package
        run: poetry build
      - name: Run smoke test
        run: |
          pip install dist/az-switch-*.whl
          # Does it actually work?
          az-switch --help
        working-directory: ./smoketest
